# Generated by Django 3.2.9 on 2021-12-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='saved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
