# Generated by Django 3.2.9 on 2021-12-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
